theme: jekyll-theme-hacker
title: LucasLWH's Homepage
description: In Progress...

owner:
  name: Lucas Lim
  avatar: bio-photo.jpg
  bio: "Hi! Lucas here."
  email:
 #Social Media Links
  linkedin: www.linkedin.com/in/lucaslwh
  github: LucasLWH
