theme: jekyll-theme-hacker
title: LucasLWH's Homepage
description: In Progress...
name: Lucas Lim
avatar: bio-photo.jpg
bio: "Hi! Lucas here."

linkedin: www.linkedin.com/in/lucaslwh
github: LucasLWH
